[package]
name = "checkasum"
version = "0.2.1"
authors = ["mc962 <11969409+mc962@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring="0.16.4"
data-encoding="2.2.1"
structopt = "0.3.14"